node {
 try  {
 notify('Job Started') 
	 
  stage('Git-Checkout') {
   git 'https://github.com/adityashankar80/FinalDemo.git'
  }
	 
 def project_path="devops/"
	 
 dir(project_path) {
    
  stage('Maven-Clean') {
   sh label: 'CLEAN', script: 'mvn clean'
  }
    
 stage('Maven-Compile') {
   sh label: 'COMPILE', script: 'mvn compile'
  }

  
   stage('Maven-Test') {
   sh label: 'TEST', script: 'mvn test'
  }
  
   stage('Maven-Package') {
   sh label: 'PACKAGE', script: 'mvn package'
  }
	 
 stage('Sonar Analysis'){
        withSonarQubeEnv('SonarQube'){
         sh 'mvn sonar:sonar'
        }
        }
	 
   stage('Archive-Artifacts') {
   archiveArtifacts 'target/*.war'
  }
  
   stage('Jfrog Artifacory Upload') {
        def server= Artifactory.server 'Artifactory'
                    def uploadSpec= """{
                        "files": [{
                        "pattern": "/root/.jenkins/workspace/Pipeline/devops/target/*.war",
                        "target": "petclinic"}]
                    }"""
        server.upload(uploadSpec)
        
        }
     
   stage('Docker-Stage-Deployment') {
   sh label: 'DOCKER DEPLOYMENT', script: 'docker-compose up -d --build'
  }
	 
 }
notify('Job Completed')   
} catch (err) {
  notify("Error ${err}")
  currentBuild.result = 'FAILURE'
 }
 }	 


def notify(status){
    emailext (
	to: "aditya.shankar@mindtree.com",
	subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
	 body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
	<p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
		)
	}
